### ISSUE TITLE
CM won't tolerate slash as directory separator on Windows

### ISSUE THREAD

**Issue by kcrary** [smlnj/legacy#293] opened 2024-01-27 17:12 UTC
On Windows, starting in version 110.99.3, CM fails when a pathname contains a slash:

    - CM.make "../ipp/basis/basis.cm";
    [scanning ..\092047ipp\092047basis\092047basis.cm]
    ../ipp/basis/basis.cm:48.9-48.18 Error: Io: openIn failed on "basis.sml", Win32TextPrimIO.openRd: failed
    ../ipp/basis/basis.cm:49.9-49.21 Error: Io: openIn failed on "smlbasis.sml", Win32TextPrimIO.openRd: failed
    val it = false : bool

The regular I/O functions (e.g., `TextIO.openIn`) still accept slashes.

CM does seem to work when one uses a backslash instead of a slash, but this is not an acceptable workaround when trying to write portable code.

This might be the same as #280.

**Comment by JohnReppy** [comment] 2024-01-28 01:59
This is indeed a duplicate of #280.  We changed the behavior of `CM.make` to use the native path format (since it is usually used in the REPL, we wanted it to be consistent with the host OS conventions).  Windows does allow `/` as a path separator, however, so we should fix the problem.

**Closed by JohnReppy** 2024-01-28 01:59 UTC
Labels: bug, duplicate, windows
