### ISSUE TITLE
`Date.fmt` fails on the `%Z` specifier for hand-constructed dates

### ISSUE THREAD

**Issue by Skyb0rg007** [smlnj/legacy#329] opened 2024-11-08 20:56 UTC
### Version

110.99.6.1 (Latest)

### Operating System

- [X] Any
- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Ubuntu on WSL

### Processor

- [X] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Basis Library

### Severity

Minor

### Description

Date.fmt sometimes throws an exception or returns the wrong result.

### Transcript

```sml
- val d = Date.date {hour=14, minute=42, second=16, day=8, month=Date.Nov, year=2024, offset=NONE};
- print (Date.fmt "%Z" d);
uncaught exception Date
  raised at: Basis/Implementation/date.sml:58.44-58.48
```

### Expected Behavior

```sml
- val d = Date.date {hour=14, minute=42, second=16, day=8, month=Date.Nov, year=2024, offset=NONE};
- print (Date.fmt "%Z" d);
CST
```

### Steps to Reproduce

Run the given code.
If you change the string to `"%Z "` (ie. include a space), the timezone string isn't printed but the exception goes away.

### Additional Information

MLton and MoscowML handle this properly.

### Email address

skyler DOT soss AT gmail DOT com

**Comment by Skyb0rg007** [comment] 2024-11-08 20:57
Note that this works with dates created with `Date.fromTimeLocal`, so it may be related to `Date.date` as well.

**Comment by JohnReppy** [comment] 2024-11-09 00:30
The root cause is that the `strftime` function in the C library is mapping the `%Z` format specifier to the empty string for this example.  As noted in the bug report, a date value created using `fromLocalTime` does not cause this issue.  I think that the problem may be that the internal representation of the date value has `NONE` as the `isDST` field, which gets mapped to `-1` in the C call.  I'm not sure how to correctly set that field for an arbitrary date value.

**Comment by JohnReppy** [comment] 2024-11-09 01:46
I've added a temporary fix for this issue to the runtime-system's
`_ml_Date_strftime` function.  A better fix will be to use the `mktime`
function as part of the date normalization process in the `Data`
module, but that will require adding a new function to the date
*C* library.

**Closed by JohnReppy** 2024-11-09 01:46 UTC
Labels: bug, basis-lib, fixed-in-110.99.7
